"""Bilingual accounting glossary (English -> Indonesian).

Covers cost types, costing methods, analysis terms, overhead, budgeting,
variance types, and general management accounting vocabulary.
Used for:
- System prompt injection (LANG-02)
- BM25 bridging entries for cross-lingual retrieval
"""

GLOSSARY: dict[str, str] = {
    # Cost types
    "overhead cost": "biaya overhead",
    "variable cost": "biaya variabel",
    "fixed cost": "biaya tetap",
    "direct cost": "biaya langsung",
    "indirect cost": "biaya tidak langsung",
    "sunk cost": "biaya tertanam",
    "opportunity cost": "biaya kesempatan",
    "marginal cost": "biaya marjinal",
    "joint cost": "biaya bersama",
    "prime cost": "biaya utama",
    "conversion cost": "biaya konversi",
    # Costing methods
    "job order costing": "kalkulasi biaya pesanan",
    "process costing": "kalkulasi biaya proses",
    "activity-based costing": "kalkulasi biaya berdasarkan aktivitas",
    "standard costing": "kalkulasi biaya standar",
    "absorption costing": "kalkulasi biaya penuh",
    "variable costing": "kalkulasi biaya variabel",
    "backflush costing": "kalkulasi biaya mundur",
    # Analysis terms
    "break-even point": "titik impas",
    "contribution margin": "margin kontribusi",
    "variance analysis": "analisis varians",
    "cost-volume-profit": "biaya-volume-laba",
    "return on investment": "pengembalian investasi",
    "residual income": "laba residual",
    "economic value added": "nilai tambah ekonomi",
    # Overhead terms
    "overhead allocation": "alokasi overhead",
    "cost driver": "pemicu biaya",
    "allocation base": "basis alokasi",
    "predetermined overhead rate": "tarif overhead yang ditentukan sebelumnya",
    "applied overhead": "overhead yang dibebankan",
    "over-applied overhead": "overhead yang dibebankan berlebih",
    "under-applied overhead": "overhead yang dibebankan kurang",
    # Budgeting
    "master budget": "anggaran induk",
    "flexible budget": "anggaran fleksibel",
    "static budget": "anggaran statis",
    "capital budgeting": "penganggaran modal",
    "operating budget": "anggaran operasional",
    # Variance types
    "material price variance": "varians harga bahan",
    "material quantity variance": "varians kuantitas bahan",
    "labor rate variance": "varians tarif tenaga kerja",
    "labor efficiency variance": "varians efisiensi tenaga kerja",
    "overhead spending variance": "varians pengeluaran overhead",
    "overhead volume variance": "varians volume overhead",
    # General
    "cost of goods sold": "harga pokok penjualan",
    "work in process": "barang dalam proses",
    "finished goods": "barang jadi",
    "raw materials": "bahan baku",
    "cost center": "pusat biaya",
    "profit center": "pusat laba",
    "investment center": "pusat investasi",
    "transfer pricing": "harga transfer",
    "relevant cost": "biaya relevan",
    "differential cost": "biaya diferensial",
    "controllable cost": "biaya terkendali",
    "uncontrollable cost": "biaya tak terkendali",
    "period cost": "biaya periode",
    "product cost": "biaya produk",
    "manufacturing overhead": "overhead pabrik",
    "selling expense": "beban penjualan",
    "administrative expense": "beban administrasi",
    "depreciation": "penyusutan",
    "amortization": "amortisasi",
    "cost allocation": "alokasi biaya",
    "equivalent units": "unit ekuivalen",
    "spoilage": "produk rusak",
    "rework": "pengerjaan ulang",
    "scrap": "sisa bahan",
    "net realizable value": "nilai realisasi bersih",
    "throughput": "throughput",
    "bottleneck": "bottleneck",
    "theory of constraints": "teori kendala",
    "balanced scorecard": "balanced scorecard",
    "just-in-time": "just-in-time",
    "total quality management": "manajemen mutu terpadu",
    "kaizen costing": "kalkulasi biaya kaizen",
    "target costing": "kalkulasi biaya target",
    "life-cycle costing": "kalkulasi biaya siklus hidup",
    # Additional terms to reach >= 100
    "cost object": "objek biaya",
    "cost pool": "kumpulan biaya",
    "activity driver": "pemicu aktivitas",
    "resource driver": "pemicu sumber daya",
    "value chain": "rantai nilai",
    "supply chain": "rantai pasokan",
    "lean manufacturing": "manufaktur ramping",
    "six sigma": "six sigma",
    "quality cost": "biaya kualitas",
    "prevention cost": "biaya pencegahan",
    "appraisal cost": "biaya penilaian",
    "internal failure cost": "biaya kegagalan internal",
    "external failure cost": "biaya kegagalan eksternal",
    "operating leverage": "leverage operasi",
    "margin of safety": "margin keamanan",
    "sensitivity analysis": "analisis sensitivitas",
    "net present value": "nilai sekarang bersih",
    "internal rate of return": "tingkat pengembalian internal",
    "payback period": "periode pengembalian",
    "profitability index": "indeks profitabilitas",
    "weighted average cost of capital": "biaya modal rata-rata tertimbang",
    "economic order quantity": "kuantitas pesanan ekonomis",
    "safety stock": "persediaan pengaman",
    "reorder point": "titik pemesanan ulang",
    "standard hours": "jam standar",
    "actual hours": "jam aktual",
    "standard rate": "tarif standar",
    "actual rate": "tarif aktual",
    "favorable variance": "varians menguntungkan",
    "unfavorable variance": "varians tidak menguntungkan",
    "cost behavior": "perilaku biaya",
    "step cost": "biaya bertahap",
    "mixed cost": "biaya campuran",
    "high-low method": "metode titik tertinggi-terendah",
    "regression analysis": "analisis regresi",
    "cost estimation": "estimasi biaya",
    "budget variance": "varians anggaran",
    "performance report": "laporan kinerja",
    "responsibility accounting": "akuntansi pertanggungjawaban",
    "decentralization": "desentralisasi",
    "segment reporting": "pelaporan segmen",
    "service department": "departemen jasa",
    "producing department": "departemen produksi",
    "direct method": "metode langsung",
    "step-down method": "metode bertahap",
    "reciprocal method": "metode timbal balik",
    "by-product": "produk sampingan",
    "split-off point": "titik pisah",
}

# Reverse glossary: Indonesian -> English
GLOSSARY_REVERSE: dict[str, str] = {id_term: en_term for en_term, id_term in GLOSSARY.items()}
